Small formatting to better align the values. Barring hte 0s...
besteon/Ironmon-Tracker pull request #40
Opened 2022-05-22 21:18 UTC by GB127

However. There is a problem : The 0s are ugly. I tried a couple of time. The fix is to remove the 0s in the formatting.

The current issue that forced me to use zeros as "proof of concept" is that the spaces' width aren't equal to the space of the digits in the font used. To replace the zeroes, we would need to change the font used for the numbers. Before I go ahead and try to edit the font (I have no idea how),  I want to confirm if that is something you want incorporated before I lose my time trying to figure this out.

I wrote this because, honestly, I prefer a aligned display. I dislike having a display like this:
```
 95
 90
 100
```
I prefer something like:
```
  95
  90
 100
```
In case this isn't shown properly on a different browser, all the hundreds should be aligned, all the tens are aligned, and all the units are aligned.

2022-05-22 21:19 UTC, GB127 commented
I will also fix the code formatting after I finish my modification if this kind of modification is welcome. Don't worry about the mess that I made with all the new lines and all.

2022-05-22 21:20 UTC, GB127 commented on ironmon_tracker/Drawing.lua
> +		Drawing.drawText(
Example of mess I made that I will fix if I get the green light.

2022-05-22 22:14 UTC, bdjeffyp commented
I hear you on the text alignment. Can you provide screenshots of what your change looks like in the tracker? I noticed that this only covers the moves section of the tracker. What about the stats?

2022-05-22 22:16 UTC, bdjeffyp commented
I'm also not certain what you mean by the first line in initial comment: "However. There is a problem : The 0s are ugly. I tried a couple of time. The fix is to remove the 0s in the formatting." Can you describe further what you mean here?

2022-05-22 22:39 UTC, GB127 commented
I wasn't bothered for the stats. But I can adjust those as well.

 "However. There is a problem : The 0s are ugly. I tried a couple of time. The fix is to remove the 0s in the formatting." Can you describe further what you mean here?

What I mean here is that I tried with formatting with spaces instead of zeros. But because spaces aren't as wide as the zeroes, I couldn't get a decent look.

Currently it only edit the PPs, move power and move accuracy.

2022-05-22 22:43 UTC, GB127 commented
Here is a page on monospaced font : https://en.wikipedia.org/wiki/List_of_monospaced_typefaces

The font used for the digits is not monospaced. That is the current issue.

2022-05-22 22:46 UTC, bdjeffyp commented
The numbers in this font are definitely fixed width. All digits are four pixels wide and use a leading empty pixel column if only 3 pixels wide (in the case of "1")

2022-05-22 22:49 UTC, bdjeffyp commented
Example screenshot:
![image](https://user-images.githubusercontent.com/5532354/169719252-974b558f-ae84-4436-bab5-4e3e38075a8e.png)
These digits are fixed width

2022-05-23 00:11 UTC, GB127 commented
But the spaces aren't it seems. Unless I misunderstand something from the lua string formatting.

From what I understand from lua scripting, the fix to replce the zeros to spaces is to simply remove the 0.
"%02s" => "%2s".

I was able to add a lot of spaces and everything moved as expected (I tried wiht something like "%8s"). But even if I put "%3s", the numbers don't align as it should be. I'm not sure what is the issue if the font used is monospaced.

2022-05-23 00:16 UTC, GB127 commented
![image](https://user-images.githubusercontent.com/62620901/169722512-f06a72a0-1fcb-4208-b6dd-16025492e1b5.png)

PP is "2%s".
Accuracy and Power are "%3s".

2022-05-23 14:27 UTC, bdjeffyp commented
@GB127, I want to personally apologize because I have misread what you are stating multiple times. I believe I understand the problem now. Just to make certain I am not messing this up again, I'll restate to make sure I have this right.

You want to align numbers, but you can't because the "space" character itself is not at a fixed width, because the whole font is a variable width font. I was overly concerned about the numbers themselves because I thought that was what you were referring to specifically. Again, I apologize. 😅

So, here is my suggestion then:
- Make a new function in the Drawing object, like `drawText`, for numbers specifically. This function needs to behave similarly to `drawText` (has two calls to `gui.drawText` for drawing the shadow and then the text) but it can use a monospace font.
- Name the new function `drawNumbers`. This will call out the fact that the function is explicitly for rendering numbers in the tracker (and any aligning spaces).
- The most important part: In the two calls to `gui.drawText` within your `drawNumbers` function, you need to choose a font family that is monospaced, but ALSO is similar to the current font. I recommend choosing a few of them and taking screenshots of the appearance so that Besteon can make the ultimate choice on which to go with, or if they'd rather stick with the current appearance.

I hope that this gives you a clearer path forward to accomplish something that can make this tracker project more aesthetically pleasing to the eye. I'm sorry again for the earlier run around and thank you for taking the effort to make this project better for everyone!

2022-05-23 17:13 UTC, GB127 commented
Noted. Will look into it today or tomorrow.

Do not worry about the misunderstanding. :)

2022-05-27 17:41 UTC, GB127 commented
-- Tested with 3 of the 4 monoscripts according to this site: https://www.autoitscript.com/autoit3/docs/appendix/fonts.htm
        -- In my opinion, Ludida Console gave the best result. Consolas gave good results too.
        -- I'm not sure what other fonts are accessible...

2022-05-27 17:41 UTC, GB127 commented
Here are the outputs:
Consolas
![consolas](https://user-images.githubusercontent.com/62620901/170763116-bae0b222-d052-41d0-b51f-f33e71b1c8d7.PNG)
Courier New
![courier new](https://user-images.githubusercontent.com/62620901/170763118-0f603e9d-ac5f-4b0f-bda7-9738ef3f8a99.PNG)
Lucida Console
![Lucida console](https://user-images.githubusercontent.com/62620901/170763126-9e38ff09-3cff-4160-bdb6-2fee8747ec42.PNG)

2022-05-27 17:46 UTC, GB127 commented
I have updated the code in my repo, but I don't know how to update this pull request...

2022-05-27 17:52 UTC, GB127 commented
Currently fixing the conflicts. Hold on...

2022-05-27 22:31 UTC, GB127 commented
Just got an idea that would allow me to avoid editing the font. I'll implement the idea tomorrow.

2022-05-29 16:37 UTC, GB127 commented
![image](https://user-images.githubusercontent.com/62620901/170881159-96ff0146-4e5e-4af9-a22c-acea9c75acdb.png)

2022-05-29 17:35 UTC, bdjeffyp commented on .gitignore
> +calculate_stat_prototyp.py
Please delete this file and recommit

2022-05-29 17:39 UTC, bdjeffyp requested changes
Aside from deleting the .gitignore, a new Settings.ini entry should also be included to give users the option to right justify the numbers or use the original style.

2022-05-29 17:45 UTC, GB127 commented on .gitignore
> +calculate_stat_prototyp.py
Oops. My bad.

2022-05-29 17:46 UTC, GB127 commented
> Aside from deleting the .gitignore, a new Settings.ini entry should also be included to give users the option to right justify the numbers or use the original style.

I have no idea how to do this...

2022-05-29 17:47 UTC, GB127 commented on .gitignore
> +calculate_stat_prototyp.py
I deleted my gitignore and recommited.

2022-05-29 17:56 UTC, GB127 commented
Here what I have done :
-> New option in settings
-> Check a bool with the setting. If justified, add a spacing. Else, add no spacing.

2022-05-30 16:51 UTC, bdjeffyp approved these changes

2022-05-30 16:51 UTC, merged