Battle effects screen
besteon/Ironmon-Tracker pull request #428
Opened 2023-10-24 02:40 UTC by jtigues

- Adds a new screen to the Tracker during trainer battles. Accessed by clicking on the pokeball icons when viewing an enemy mon
- The screen can show Statuses of individual mons, as well as effects applied to either side of the battle, and the whole battle. User can switch between the different views by 
- The screen allows users to see passive Battle Effects which the game has notified them of, but cannot otherwise be reminded of once the next turn starts.
- Some examples: Weather conditions, Leech Seed and which mon will receive the HP, Taunt, Encore, Confusion, Reflect/Light Screen, pending Future Sight attacks, or the number of times an enemy has successfully Protected consecutively.
![image](https://github.com/besteon/Ironmon-Tracker/assets/12836386/1f4fa9c8-fbf5-4ead-a9dd-a80e41ebe57c)

There is one known and incredibly minor bug I have not been able to sort out: I cannot for the life of me get the text & buttons to appear with shadows, and it seems it should work fine enough. But functionally, everything works fine across Games and Languages.
Also, I don't know where this expYield removal change came from, if I need to go in and manually re-add all of those that's fine.

2023-10-24 03:55 UTC, jtigues commented
Few small things I've noticed looking back over it:
- "stale" flag is no longer used but still has references
- BattleEffectsScreen Button is being drawn unnecessarily, the button is invisible
- Left Arrow pixel image has an extra column of 0s, it's actually 10 by 9.

2023-10-24 09:58 UTC, Fellshadow requested changes
the removal of the `ExpYield` in the PR is really weird to me
On the PR itself it looks like [this commit](https://github.com/besteon/Ironmon-Tracker/pull/428/commits/7c546b601acd10da9b0c02b1a07d647ac806ddd4) is the one github thinks is removing it, but weirdly the same commit doesn't look like that at all on the actual branch's commit history (7c546b601acd10da9b0c02b1a07d647ac806ddd4)?

What's even weirder is that the merge commit from Zac merging in the PR is present on the branch's commits *but* it doesn't seem to be there when viewing the [files on the branch](<https://github.com/jtigues/Ironmon-Tracker/tree/BattleEffectsScreen/ironmon_tracker/Languages>)?

I think the commit history got messed up somewhere somehow 🤔 idk if a rebase would work? Rest of the code seems fine though (Aside from what you've mentioned and the one comment below) so manually adding back in also would be fine i think, though commit history may/may not be messy

2023-10-24 13:21 UTC, jtigues commented on ironmon_tracker/screens/BattleEffectsScreen.lua
> +	local battleTerrain = Memory.readbyte(0x02022ff0)
Fixed, ty

2023-10-24 13:27 UTC, jtigues commented
> Few small things I've noticed looking back over it:
> 
> * "stale" flag is no longer used but still has references
> * BattleEffectsScreen Button is being drawn unnecessarily, the button is invisible
> * Left Arrow pixel image has an extra column of 0s, it's actually 10 by 9.

Fixed

2023-10-24 18:03 UTC, UTDZac requested changes
I quickly reviewed the files that weren't the large `BattleEffectsScreen.lua` file, I'll review that one later.

As a note for that file though, I noticed quite a few functions that were defined as global, such as `function loadFieldEffects()`. If this function is only meant to be used within this file, use `local function loadFieldEffects()`, otherwise, preface it with the filename: `function BattleEffectsScreen.loadFieldEffects()`.

I also recommend making two changes to the `initialize() function:
- Move this as far up to the top of the file as possible, its usually the first important thing that should be seen for any given screen file
- Include any `BattleEffectsScreen.variablename` that have defined defaults that can change in this function. Quickloading does not reset those variables, so you must reset them in this function (called when the tracker starts up).
   - For example: The variable `viewedMonIndex` is one that I'd expect to change as I play the game. It needs to be set to its default value in `initialize()`, otherwise if I reset my game while its some other value, my new game will be using the old value.

2023-10-24 18:45 UTC, jtigues commented on ironmon_tracker/Constants.lua
> +	},
Done. Yeah I figured everything else was a square so it was just a convention

2023-10-24 18:48 UTC, jtigues commented on ironmon_tracker/Utils.lua
> +function Utils.generatebitwisemap(value, size)
Done

2023-10-24 18:51 UTC, jtigues commented on ironmon_tracker/Languages/English.lua
> +		Title = "BATTLE EFFECTS",
Done

2023-10-24 18:56 UTC, jtigues commented on ironmon_tracker/screens/TrackerScreen.lua
> +		text = "",
Done

2023-10-24 18:58 UTC, jtigues commented on ironmon_tracker/Utils.lua
> +		end
Done

2023-10-24 19:16 UTC, jtigues commented
expYield has been added back in, and the various concerns with the syntax/formatting have been resolved.

Also added the text strings to the non-English files, oops.

2023-10-26 18:04 UTC, UTDZac approved these changes

2023-10-26 22:33 UTC, Fellshadow approved these changes
Nothing major from me, just the little bits of cleanup stuff I mentioned in the discord
Will leave open since Zac is wanting to do some testing

2024-12-24 20:52 UTC, merged