Manual Hidden Power Feature
besteon/Ironmon-Tracker pull request #65
Opened 2022-06-02 09:22 UTC by Brian0255

So I thought it might be nice to let the player change the move type of Hidden Power manually (as opposed to it being calculated automatically somehow). This would allow a bit of convenience without being overly automated. My idea that I have implemented here is allowing the player to click the move's name to cycle through types, with the color, STAB effectiveness, and move effectiveness all changing dynamically.

The way I did this is to add a special Hidden Power button that is only drawn when the player has the move. If they have it, it gets drawn where the move would normally go, and responds to clicks accordingly. The tracker will store what the player has manually selected as Hidden Power's type, making it so that enemy mons with Hidden Power will still default to normal type.

I've tested this and it should work fully, so I would love to hear your thoughts on this feature or any changes I should make!

Here's a video as well:

https://user-images.githubusercontent.com/61294586/171597645-8c022839-71c5-481e-bf9e-65a8eb817bd4.mp4

2022-06-02 19:07 UTC, Brian0255 commented
Thanks, great catch! I completely forgot about that and have updated it.

2022-06-03 01:13 UTC, bdjeffyp requested changes
This is a great alternative to having to use the Notes feature while also being able to make use of the move effectiveness feature. Thanks for doing this, OnlySpaghettiCode! I only had a few things I'd like addressed before merging.

2022-06-03 01:13 UTC, bdjeffyp commented on ironmon_tracker/Utils.lua
> +		if moveType== type then
nit: put a space between `moveType` and `==`

2022-06-03 01:13 UTC, bdjeffyp commented on ironmon_tracker/Program.lua
> +function Program.playerHasMove(moveName)
Can this be placed in Utils.lua? I feel like it is better scoped as a utility function rather than a main program function.

2022-06-03 02:02 UTC, bdjeffyp approved these changes

2022-06-03 02:02 UTC, merged

2022-06-03 02:02 UTC, bdjeffyp commented
Merged! Thanks again for another great addition!